#test
#8080

server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  security:
    user:
      name: user
      password: 123
  messages:
    basename: errors

  datasource: # jdbc
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
      defer-datasource-initialization: true

  thymeleaf:
    cache: true #운영시 true
    enabled: true

  servlet: #fileupload
    multipart:
      max-file-size: 20MB
      enabled: true

  mail: #email
    host: smtp.gmail.com
    port: 587
    username: dev.hsayho@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp

#logging:
#  file:
#    path: D:/logs
#  level:
#    root: info
#  logback:
#    rolling policy:
#      max-history: 10
#      max-file-size: 500MB