#portfolio
#3205

server:
  port: 3205

spring:
  sql:
    init:
      mode: always
  security:
    user:
      name: user
      password: 123
  devtools:
    livereload:
      enabled: true
  messages:
    basename: errors


  datasource: # jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seho0218.synology.me:3306/scheduler_portfolio?characterEncoding=utf-8
    username: root
    password: Root123!@#


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    open-in-view: false

    hibernate:
      ddl-auto: validate


    properties:
      hibernate:
        format_sql: true
        show_sql: true
      hibernate.highlight_sql: true
      defer-datasource-initialization: true


  mvc: #mvc structure
    view:
      prefix: /templates/
      suffix: .html

  thymeleaf:
    cache: false #운영시 true
    enabled: true


  servlet: #fileupload
    multipart:
      max-file-size: 20MB
      enabled: true


  mail: #email
    host: smtp.gmail.com
    port: 587
    username: ghdtpgh8913@gmail.com
    password: !@#opxxcbvy1jwdfmyiz!@#
    properties:
      mail:
        smtp:
          starttls.enable: true
          auth: true


logging.level:
  root: info
  org.hibernate.SQL: debug


