server:
  port: 8090

spring:
  sql:
    init:
      mode: always
  security:
    user:
      name: user
      password: 123

  datasource: # jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/scheduler?characterEncoding=utf-8
    username: root
    password: root1234


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      format_sql: true
      show_sql: true
      hibernate.highlight_sql: true
      defer-datasource-initialization: true


  mvc:
    view:
      prefix: /templates/
      suffix: .html


  servlet: #fileupload
    multipart:
      max-file-size: 20MB
      enabled: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: #email
    password: #appPassword
    properties:
      mail:
        smtp:
          starttls.enable: true
          auth: true


logging.level:
  root: info
  org.hibernate.SQL: debug


mybatis:
  type-aliases-package: com.attendance.scheduler.dto
  mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true



